-- Support managing Nachrichtenvorlagen (message templates) from the admin app.
--
-- The `nachrichten` table already existed for reading message templates, but
-- was never brought under version control and, like the tables covered by
-- issue #40, had no Row Level Security policy. Now that the admin app also
-- creates, edits and deletes templates through the anon key, make sure the
-- table exists with the columns the app writes to and is restricted to
-- authenticated users the same way the other tables are.
--
-- See: https://github.com/DerDawo/OptikSystemMVP/issues/54

create table if not exists public.nachrichten (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Titel" text,
  "Text" text
);

alter table public.nachrichten add column if not exists "Titel" text;
alter table public.nachrichten add column if not exists "Text" text;

alter table public.nachrichten enable row level security;

drop policy if exists "Authenticated users can manage nachrichten" on public.nachrichten;
create policy "Authenticated users can manage nachrichten" on public.nachrichten
  for all
  to authenticated
  using (true)
  with check (true);
