-- Terminverwaltung: neue Tabelle fuer Kundentermine (z.B. Einschleifen,
-- Abholung, Kontrolle, Refraktion).
--
-- See: https://github.com/DerDawo/OptikSystemMVP/issues/50

create table if not exists public.termin (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kunde_id bigint not null references public.kunde (id),
  "Start" timestamptz not null,
  "Ende" timestamptz not null,
  "Terminart" character varying,
  "Notiz" text
);

comment on table public.termin is 'Termine der Kunden (z.B. Einschleifen, Abholung, Kontrolle, Refraktion)';

create index if not exists termin_kunde_id_idx on public.termin (kunde_id);
create index if not exists termin_start_idx on public.termin ("Start");

-- RLS konsistent mit den uebrigen Tabellen (siehe
-- 20260828000000_restrict_access_to_authenticated_users.sql): nur
-- authentifizierte Benutzer duerfen lesen/schreiben.
alter table public.termin enable row level security;

drop policy if exists "Authenticated users can manage termin" on public.termin;
create policy "Authenticated users can manage termin" on public.termin
  for all
  to authenticated
  using (true)
  with check (true);
