-- Add a dedicated order type for contact lenses, analogous to the existing
-- "brille" (glasses) orders.
--
-- See: https://github.com/DerDawo/OptikSystemMVP/issues/49

create table public.kontaktlinse (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kunde_id bigint references public.kunde (id) on delete cascade,
  "Berater" text,
  "Datum" date,
  "Abholung" date,
  "Notizen" text,
  "Nachkontrolltermin" date,
  "LinsentypLinks" text,
  "RadiusLinks" numeric,
  "DurchmesserLinks" numeric,
  "SphLinks" numeric,
  "CylLinks" numeric,
  "AchseLinks" numeric,
  "MaterialLinks" text,
  "HerstellerLinks" text,
  "TragemodusLinks" text,
  "PreisLinks" numeric,
  "LinsentypRechts" text,
  "RadiusRechts" numeric,
  "DurchmesserRechts" numeric,
  "SphRechts" numeric,
  "CylRechts" numeric,
  "AchseRechts" numeric,
  "MaterialRechts" text,
  "HerstellerRechts" text,
  "TragemodusRechts" text,
  "PreisRechts" numeric,
  "Summe" numeric
);

comment on table public.kontaktlinse is 'Kontaktlinsen-Aufträge eines Kunden, analog zu public.brille.';

alter table public.kontaktlinse enable row level security;

drop policy if exists "Authenticated users can manage kontaktlinse" on public.kontaktlinse;
create policy "Authenticated users can manage kontaktlinse" on public.kontaktlinse
  for all
  to authenticated
  using (true)
  with check (true);
