-- Dokumentenvorlagen-Bibliothek (#58): generische Grundlage fuer druckbare
-- Dokumente aus der Brillenkartei (Sehtest, Werkstattkarte,
-- Berechtigungsschein, Privatrezept, Rezeptdruck Arzt, Reparaturschein) sowie
-- fuer die spaeter darauf aufbauenden Rechnungen (#56) und Mahnungen (#57).
--
-- Der Vorlagentext enthaelt Platzhalter im gleichen Merge-Field-Muster wie
-- die Nachrichtenvorlagen (siehe messaging.ts/kunden.tsx), aber namespaced
-- nach Entitaet, z. B. {{kunde.vorname}} oder {{brille.summe}}. Damit lassen
-- sich neue Vorlagen (auch fuer Rechnung/Mahnung) rein datenseitig ergaenzen,
-- ohne die Dialog-/Render-Logik im Admin-Frontend anzufassen.
--
-- See: https://github.com/DerDawo/OptikSystemMVP/issues/58

create table if not exists public.dokumentvorlage (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Name" text not null,
  "Kategorie" text not null,
  "Vorlagentext" text not null default '',
  "Aktiv" boolean not null default true
);

comment on table public.dokumentvorlage is 'Bearbeitbare Vorlagen fuer druckbare Dokumente (Sehtest, Werkstattkarte, Rechnung, Mahnung, ...), Platzhalter im Format {{entitaet.feld}}';

alter table public.dokumentvorlage
  drop constraint if exists dokumentvorlage_kategorie_check;
alter table public.dokumentvorlage
  add constraint dokumentvorlage_kategorie_check check ("Kategorie" in (
    'Sehtest',
    'Werkstattkarte',
    'Berechtigungsschein',
    'Privatrezept',
    'Rezeptdruck Arzt',
    'Reparaturschein',
    'Rechnung',
    'Mahnung'
  ));

create index if not exists dokumentvorlage_kategorie_idx on public.dokumentvorlage ("Kategorie");

-- RLS konsistent mit den uebrigen Tabellen (siehe
-- 20260828000000_restrict_access_to_authenticated_users.sql): nur
-- authentifizierte Benutzer duerfen lesen/schreiben.
alter table public.dokumentvorlage enable row level security;

drop policy if exists "Authenticated users can manage dokumentvorlage" on public.dokumentvorlage;
create policy "Authenticated users can manage dokumentvorlage" on public.dokumentvorlage
  for all
  to authenticated
  using (true)
  with check (true);
