-- Ergänzung zu 20260101000000_baseline_genesis_schema.sql: `nachrichten`
-- existierte (wie die dort beschriebenen Tabellen) bereits vor Einführung
-- der Migrationsverwaltung, mit den Spalten "bezeichnung" und "template"
-- (kleingeschrieben, ohne created_at - anders als alle sonstigen Tabellen).
-- 20260830140000_nachrichten_crud.sql legt die Tabelle zwar mit
-- `create table if not exists` an, enthält dabei aber nur "Titel"/"Text"
-- (PascalCase) - ohne diese Migration hier fehlen "bezeichnung"/"template"
-- auf einem frisch aus `supabase/migrations/` aufgebauten Projekt.
--
-- Idempotent, aus demselben Grund wie die Baseline-Migration.

create table if not exists public.nachrichten (
  id bigint generated by default as identity primary key,
  bezeichnung text,
  template text
);
