-- Baseline-Schema aus der Zeit vor Einführung der Migrationsverwaltung.
--
-- kunde, brille, glass, glastyp, fassung, zusatzleistung,
-- brille_hat_zusatzleistungen und kunde_leistet_zauzahlung_fuer_brille wurden
-- ursprünglich über den Supabase Studio Table Editor angelegt, bevor
-- `supabase/migrations/` genutzt wurde (siehe Kommentar in
-- 20260830235900_fix_brille_hat_zusatzleistungen_column_casing.sql). Es gab
-- dafür bislang keine eingecheckte Migration, wodurch ein frisches Supabase-
-- Projekt (z. B. ein neuer Dev-/Prod-Branch oder -Projekt) nicht allein aus
-- `supabase/migrations/` aufgebaut werden konnte - alle nachfolgenden
-- Migrationen setzen diese Tabellen bereits voraus.
--
-- Diese Migration rekonstruiert den Stand dieser Tabellen so, wie er beim
-- allerersten Lauf von 20260828000000_restrict_access_to_authenticated_users.sql
-- vorlag (per Introspektion des laufenden Projekts ermittelt). Sie muss vor
-- allen anderen Migrationen laufen (Zeitstempel entsprechend früh gewählt).
--
-- "BrillenArt" (brille) und "Bezeichnung" (zusatzleistung) waren ursprünglich
-- eigene Enum-Typen, die von 20260830130000_add_brillenart_stammdaten.sql
-- bzw. 20260830120000_zusatzleistung_kategorie_und_rabatt.sql per
-- `alter column ... type text` + `drop type if exists ...` auf text
-- umgestellt wurden. Da beide Migrationen `drop type if exists` verwenden,
-- werden die Spalten hier direkt als text angelegt (funktional identisch,
-- ohne die längst entfernten Enum-Typen erneut anzulegen).
--
-- Bewusst durchgängig idempotent (`create table if not exists`, Typen nur
-- anlegen falls nicht vorhanden): So kann diese Migration auch gegen das
-- bestehende Dev-Projekt angewendet werden, in dem diese Tabellen bereits
-- existieren (sie ist dort dann ein No-Op, wird aber in der
-- Migrationshistorie erfasst) - nur so bleibt `supabase/migrations/`
-- projektübergreifend als vollständige, alleinige Quelle nutzbar.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'anrede' and typnamespace = 'public'::regnamespace) then
    create type public.anrede as enum ('Frau', 'Herr', 'Prof.', 'Prof. Dr.', 'Dr.');
  end if;
  if not exists (select 1 from pg_type where typname = 'krankenversicherung' and typnamespace = 'public'::regnamespace) then
    create type public.krankenversicherung as enum ('Privat Krankenversichert', 'Gesetzlich Krankenversichert', 'Unbekannt');
  end if;
  if not exists (select 1 from pg_type where typname = 'seite' and typnamespace = 'public'::regnamespace) then
    create type public.seite as enum ('Links', 'Rechts');
  end if;
end $$;

create table if not exists public.kunde (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "KundenNummer" varchar,
  "Aufnahmedatum" timestamptz,
  "Anrede" public.anrede not null,
  "Nachname" varchar,
  "Vorname" varchar,
  "Geburtsdatum" timestamp,
  "Geschlecht" varchar,
  "Straße" varchar,
  "Tätigkeit" varchar,
  "TelefonnummerPrivat" varchar,
  "Email" varchar,
  "KrankenkassenNummer" varchar,
  "VersichertenNummer" varchar,
  "Postleitzahl" varchar,
  "Hausnummer" varchar,
  "Stadt" varchar,
  "TelefonnummerGeschaeftlich" varchar,
  "KrankenversicherungsTyp" public.krankenversicherung,
  last_viewed_at timestamptz default (now() - interval '8 days')
);
comment on table public.kunde is 'Alle Kunden von Robert Ulm';

create table if not exists public.glass (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Sph" numeric,
  "Cyl" numeric,
  "A" numeric,
  "PD" numeric,
  "Add" numeric,
  "y_h" numeric,
  "Pr" numeric,
  "B" numeric,
  "HSA" numeric,
  "Vis" numeric,
  "iod" numeric,
  "Liefern" boolean not null default false,
  "Betrag" numeric,
  "Seite" public.seite
);
comment on table public.glass is 'Gläser für eine Brille';

create table if not exists public.fassung (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Lagernummer" varchar,
  "Bezeichnung" varchar,
  "Linie" varchar,
  "Farbe" varchar,
  "Groesse" varchar,
  "Betrag" numeric,
  "Hersteller" varchar
);
comment on table public.fassung is 'Fassungen für eine Brille';

create table if not exists public.glastyp (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Bezeichnung" varchar,
  "Hersteller" varchar,
  "Verguetung" varchar,
  "GlasGroesse" varchar,
  "Sonstiges" varchar,
  "Bestellstatus" varchar,
  "Farbe" varchar
);
comment on table public.glastyp is 'Glastypen für Brillen';

create table if not exists public.zusatzleistung (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Bezeichnung" text,
  "Betrag" numeric
);
comment on table public.zusatzleistung is 'Zusatzleistungen im Zusamenahng mit Brillen';

create table if not exists public.brille (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Berater" varchar,
  "Refraktion" varchar,
  "Datum" timestamptz,
  "Werkstatt" varchar,
  "Abholung" timestamptz,
  "Notizen" text,
  "GlasLinks" bigint references public.glass(id),
  "GlasRechts" bigint references public.glass(id),
  "Fassung" bigint references public.fassung(id),
  "Glastyp" bigint references public.glastyp(id),
  "RabattBezeichnung" varchar,
  "Summe" numeric,
  "BrillenArt" text,
  kunde_id bigint references public.kunde(id)
);
comment on table public.brille is 'Alle Brillen von allen Kunden';

create table if not exists public.brille_hat_zusatzleistungen (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  brille_id bigint references public.brille(id),
  zusatzleistung_id bigint references public.zusatzleistung(id)
);

create table if not exists public.kunde_leistet_zauzahlung_fuer_brille (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "KundenID" bigint references public.kunde(id),
  "BrillenID" bigint references public.brille(id),
  "Datum" timestamp,
  "Betrag" numeric,
  "Restbetrag" numeric
);
comment on table public.kunde_leistet_zauzahlung_fuer_brille is 'Alle Zuzahlungen, die ein Kunde für eine Brille geleistet hat';
