-- Add a maintainable master data table for "Brillenart" (type of glasses),
-- so the value can be offered as a select/autocomplete list in the frontend
-- instead of being a plain free-text field.
--
-- `brille.BrillenArt` stays a free-text column on purpose: this keeps
-- existing records intact and still allows users to enter a value that is
-- not (yet) part of the maintained list. Existing distinct values are
-- backfilled into the new table below so they keep showing up correctly
-- as a selectable choice instead of appearing blank.
--
-- See: https://github.com/DerDawo/OptikSystemMVP/issues/55

create table if not exists public.brillenart (
  id bigint generated by default as identity primary key,
  "Bezeichnung" text not null unique,
  created_at timestamptz not null default now()
);

alter table public.brillenart enable row level security;

drop policy if exists "Authenticated users can manage brillenart" on public.brillenart;
create policy "Authenticated users can manage brillenart" on public.brillenart
  for all
  to authenticated
  using (true)
  with check (true);

insert into public.brillenart ("Bezeichnung")
values
  ('Arbeitsplatzbrille'),
  ('Arbeitsschutzbrille nach DIN EN 166'),
  ('Autobrille'),
  ('Bifokalbrille'),
  ('Computerarbeitsplatzbrille (BildschArbV §6)'),
  ('Elektronische Sehhilfe'),
  ('Ersatzbrille'),
  ('Fernbrille'),
  ('Gleitsichtbrille'),
  ('Lesebrille'),
  ('Nachtsichtbrille'),
  ('Sonnenbrille mit Sehstärke'),
  ('Sportbrille')
on conflict ("Bezeichnung") do nothing;

-- Backfill any distinct free-text values already used on existing `brille`
-- records so they remain available as a choice after the frontend switches
-- to a select/autocomplete field.
insert into public.brillenart ("Bezeichnung")
select distinct "BrillenArt"
from public.brille
where "BrillenArt" is not null and btrim("BrillenArt") <> ''
on conflict ("Bezeichnung") do nothing;
